const
  cIni =
    '[Init]'#13#10 +
    'CheckUserReqCfgID=0'#13#10 +
    'CheckIntfReqCfgID=0'#13#10 +
    'MainFormCfgID=0'#13#10 +
    'ConfFormCfgID=0'#13#10 +
    'DeleteReqCfgID=0'#13#10 +
    'InsertReqCfgID=0'#13#10 +
    'UpdateReqCfgID=0'#13#10 + #13#10 +
    '[Config]'#13#10 +
    'DataSetClassName='#13#10 +
    'DataSetLibName='#13#10 +
    'DataSetProcName='#13#10 +
    'DataSetType='#13#10 +
    'SQLText='#13#10 +
    'FieldNames='#13#10 +
    'FieldDataTypes='#13#10 +
    'FieldDataSenses='#13#10 +
    'FieldSizes='#13#10 +
    'ParamNames='#13#10 +
    'ParamDataTypes='#13#10 +
    'ParamDataSense='#13#10 +
    'ParamSizes='#13#10 + #13#10 +
    '[Path]'#13#10 +
    'Bin=..\Bin\'#13#10 +
    'Cfg=..\Cfg\'#13#10 +
    'Lib=..\Lib\'#13#10 +
    'Temp=..\Temp\'#13#10 + #13#10 +
    '[Manager]'#13#10 +
    'ProjectFileName=proj.dat'#13#10 +
    'ProjectMacroUserName=%UserName%'#13#10 +
    'ProjectMacroPassword=%Password%'#13#10 +
    'LibInfoProcName=LibInfo'#13#10 +
    'LibCheckComp=False'#13#10 +
    'ImageListDelimiter=:'#13#10 +
    'ClassTypeDelimiter=:'#13#10 + #13#10 +
    '[Param]'#13#10 +
    'DatabaseName=Base'#13#10 +
    'UserName=UserName'#13#10 +
    'UserID=UserID'#13#10 +
    'InterfaceName=IntfName'#13#10 +
    'InterfaceID=IntfID'#13#10 +
    'SelectDataSetName=SelectDataSetName'#13#10 +
    'DeleteDataSetName=DeleteDataSetName'#13#10 +
    'InsertDataSetName=InsertDataSetName'#13#10 +
    'UpdateDataSetName=UpdateDataSetName'#13#10 + #13#10 +
    '[DefValue]'#13#10 +
    'UserName='#13#10 +
    'ProjectName=';