const
  cIni =
    '[Init]'#13#10 +
    'RequestClassName='#13#10 +
    'RequestLibName='#13#10 +
    'RequestProcName='#13#10 +
    'RequestXMLText='#13#10 +
    'CheckUserReqCfgID=0'#13#10 +
    'CheckIntfReqCfgID=0'#13#10 +
    'MainFormCfgID=0'#13#10 +
    'ConfFormCfgID=0'#13#10 + #13#10 +
    '[Path]'#13#10 +
    'Bin=..\Bin\'#13#10 +
    'Cfg=..\Cfg\'#13#10 +
    'Lib=..\Lib\'#13#10 +
    'Temp=..\Temp\'#13#10 + #13#10 +
    '[Project]'#13#10 +
    'FileName=proj.dat'#13#10 +
    'MacroUserName=%UserName%'#13#10 +
    'MacroPassword=%Password%'#13#10 + #13#10 +
    '[Library]'#13#10 +
    'LibInfoProcName=LibInfo'#13#10 +
    'CheckComp=False'#13#10 + #13#10 +
    '[ImageList]'#13#10 +
    'Delimiter=:'#13#10 +
    '[Param]'#13#10 +
    'DatabaseName=Base'#13#10 +
    'UserName=UserName'#13#10 +
    'UserID=UserID'#13#10 +
    'IntfName=IntfName'#13#10 +
    'IntfID=IntfID'#13#10 + #13#10 +
    '[DefValue]'#13#10 +
    'UserName='#13#10 +
    'ProjectName=';